---
abstract: Perl extension for finding the memory usage of Perl variables
author:
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Size
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  Devel::Size::Report: 0.11
requires:
  DynaLoader: 0
version: 0.70
